# Site settings
title: Martin Colahan
const-title: Under Construction
header-img: img/home-bg.jpg
construction-img: img/under-construction-bg.jpg
email: your-email@yourdomain.com
copyright_name: Martin Colahan
description: ""
#baseurl: "startbootstrap-clean-blog-jekyll"
url: "www.martincolahan.com"
twitter_username: MartinColahan
github_username:  mcolahan
facebook_username:  martin.colahan
email_username:  martin.l.colahan@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
